# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15HwLsqqn6dQnRFrpJMzv0JQIsc4HsSlY
"""

# Importar bibliotecas necesarias
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
# Crear un DataFrame de ejemplo
start_date = '2024-01-01' # Fecha de inicio
end_date = '2025-05-31' # Fecha de finalización
n_registros = (pd.to_datetime(end_date) - pd.to_datetime(start_date)).days + 1 # Total de días
entre las fechas
# Simulación de un DataFrame con las fechas
df = pd.DataFrame() # Inicializar DataFrame
df['Fecha'] = pd.date_range(start=start_date, end=end_date, freq='D') # Generar rango de
fechas
# Simular datos para la columna 'TiempoEntrega' (ajusta el rango según lo que necesites)
np.random.seed(0) # Para reproducibilidad
df['TiempoEntrega'] = np.random.randint(1, 10, size=n_registros) # Genera valores aleatorios
entre 1 y 10
# Verificar las columnas
print(df.head())
print(df.columns)
# Tendencias del Tiempo de Entrega
plt.figure(figsize=(12, 6))
plt.plot(df.groupby('Fecha')['TiempoEntrega'].mean(), color='skyblue', label='Tiempo de
Entrega Promedio')
plt.xlabel('Fecha')
plt.ylabel('Tiempo de Entrega (días)')
plt.title('Análisis de Tendencias del Tiempo de Entrega')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()
El análisis de tendencias del tiempo de entrega proporciona una visión clara de cómo varían
los tiempos de entrega de los productos a lo largo del tiempo.