# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15HwLsqqn6dQnRFrpJMzv0JQIsc4HsSlY
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# Ejemplo de datos: puedes sustituirlo por tu DataFrame
data = {
'TiempoEntrega': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
'Quejas': [0, 1, 3, 2, 5, 6, 7, 8, 9, 10]
}
df = pd.DataFrame(data)
# Verificar que no haya valores nulos
print(df[['TiempoEntrega', 'Quejas']].isnull().sum())
# Crear el diagrama de dispersión
plt.figure(figsize=(12, 6))
sns.scatterplot(x='TiempoEntrega', y='Quejas', data=df)
plt.xlabel('Tiempo de Entrega (días)')
plt.ylabel('Número de Quejas')
plt.title('Diagrama de Correlación entre Tiempo de Entrega y Quejas')
plt.grid(True)
plt.tight_layout()
plt.show()