# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15HwLsqqn6dQnRFrpJMzv0JQIsc4HsSlY
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# Configurar para gráficos en línea
# %matplotlib inline
# Establecer la semilla para reproducibilidad
np.random.seed(42)
# Simular datos de evaluación 360º
evaluacion_360 = {
'Categoría': ['Clientes', 'Empleados', 'Administradores'],
'Satisfacción': [np.random.uniform(3.5, 5.0) for _ in range(3)], # Puntajes promedio de
satisfacción
'Comentarios': [
'La calidad de los productos es excelente.',
'La comunicación interna necesita mejorar.',
'Los tiempos de entrega son a veces inaceptables.'
]
}
# Crear un DataFrame de evaluación
df_evaluacion = pd.DataFrame(evaluacion_360)
# Mostrar el DataFrame
print("Evaluación 360°:")
print(df_evaluacion)
# Gráfico de Satisfacción
plt.figure(figsize=(10, 6))
plt.barh(df_evaluacion['Categoría'], df_evaluacion['Satisfacción'], color='lightblue')
plt.xlim(0, 5)
plt.xlabel('Satisfacción (1 a 5)')
plt.title('Evaluación 360° de Satisfacción')
plt.grid(axis='x')
plt.show()