# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15HwLsqqn6dQnRFrpJMzv0JQIsc4HsSlY
"""

# Parámetros de la Función de Pérdida de Taguchi
target_time = 5 # Tiempo objetivo de entrega en días
penalty_factor = 1 # Factor de penalización para la pérdida
# Función de pérdida de Taguchi
def taguchi_loss(time, target, penalty):
return penalty * (time - target) ** 2
df['PérdidaTaguchi'] = taguchi_loss(df['TiempoEntrega'], target_time, penalty_factor)
# Histograma de la Pérdida de Taguchi
plt.figure(figsize=(12, 6))
plt.hist(df['PérdidaTaguchi'], bins=20, color='skyblue', edgecolor='black')
plt.xlabel('Pérdida de Taguchi')
plt.ylabel('Frecuencia')
plt.title('Histograma de la Pérdida de Taguchi')
Gestión del conocimiento
2024 – I
59
plt.grid(True)
plt.tight_layout()
plt.show()