# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15HwLsqqn6dQnRFrpJMzv0JQIsc4HsSlY
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
# Configurar gráficos en línea
# %matplotlib inline
# Establecer la semilla para reproducibilidad
np.random.seed(42)
# Simular datos de tiempos de entrega (en días)
# Supongamos que la mayoría de los tiempos de entrega están entre 2 y 7 días, pero con
algunos valores extremos
tiempos_entrega = np.random.normal(loc=5, scale=2, size=500).clip(1, 15) # clip para que
no haya tiempos negativos
# Crear el histograma
plt.figure(figsize=(10, 6))
plt.hist(tiempos_entrega, bins=15, color='lightblue', edgecolor='black')
plt.xlabel('Tiempo de Entrega (días)')
plt.ylabel('Frecuencia')
plt.title('Histograma de Tiempos de Entrega - Peruvian Veef')
plt.grid(True)
plt.tight_layout()
plt.show()
Simula el tiempo de entrega de tus productos en días, asumiendo que la mayoría de los
pedidos se entregan en un rango de 2 a 7 días.