# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15HwLsqqn6dQnRFrpJMzv0JQIsc4HsSlY
"""

# Importar las bibliotecas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# Definir los productos de Peruvian Veef y sus probabilidades
productos = ['Anticucho', 'Hamburguesa Veggie', 'Jamón Vegetal', 'Ensalada', 'Tacos Veganos',
'Empanadas']
probabilidades = [0.35, 0.25, 0.15, 0.10, 0.10, 0.05] # Ajustar para que sumen 1.0
# Simular 500 pedidos
np.random.seed(42) # Para reproducibilidad
pedidos = np.random.choice(productos, size=500, p=probabilidades)
# Convertir los resultados en un DataFrame
df_pedidos = pd.DataFrame(pedidos, columns=['Producto'])
# Contar la cantidad de pedidos por producto
conteo_productos = df_pedidos['Producto'].value_counts()
# Calcular el porcentaje acumulado
porcentaje_acumulado = conteo_productos.cumsum() / conteo_productos.sum() * 100
# Crear el gráfico de Pareto
fig, ax1 = plt.subplots()
# Cambiar el tamaño de la fuente y el grosor de las barras
ax1.bar(conteo_productos.index, conteo_productos, color='C0')
ax1.set_xlabel('Producto', fontsize=12) # Cambia el tamaño de la fuente
ax1.set_ylabel('Cantidad de Pedidos', color='C0', fontsize=12) # Cambia el tamaño de la
fuente
plt.xticks(rotation=45, ha='right', fontsize=10) # Rotar y ajustar las etiquetas del eje x
# Crear el segundo eje para el porcentaje acumulado
ax2 = ax1.twinx()
ax2.plot(conteo_productos.index, porcentaje_acumulado, color='C1', marker='D', ms=7,
lw=2) # Aumenta el grosor de la línea y el tamaño de los marcadores
ax2.set_ylabel('Porcentaje Acumulado', color='C1', fontsize=12) # Cambia el tamaño de la
fuente
# Líneas de referencia del 80%
ax2.axhline(y=80, color='r', linestyle='--', linewidth=2) # Ajustar el grosor de la línea
plt.title('Diagrama de Pareto de Pedidos - Peruvian Veef', fontsize=14)
plt.tight_layout() # Ajusta los márgenes para que todo se vea correctamente
plt.show()