# -*- coding: utf-8 -*-
"""Escenario Pruebas-GCV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P6BzlWaGF72yIP5zT1gysvhprrExNWvw
"""

import pandas as pd

# Crear un DataFrame de ejemplo con Quejas y Sugerencias
data = {
    'TiempoEntrega': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Quejas': [0, 1, 3, 2, 5, 6, 7, 8, 9, 10],
    'Sugerencias': [0, 1, 2, 1, 0, 1, 2, 1, 1, 0]  # Sugerencias de ejemplo
}
df = pd.DataFrame(data)

# Análisis de Quejas y Sugerencias
quejas_y_sugerencias = df[['Quejas', 'Sugerencias']].sum()
print("Total de Quejas:", quejas_y_sugerencias['Quejas'])
print("Total de Sugerencias:", quejas_y_sugerencias['Sugerencias'])

# @title PedidosDevueltos vs CostoPedido

from matplotlib import pyplot as plt
data.plot(kind='scatter', x='PedidosDevueltos', y='CostoPedido', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)