# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15HwLsqqn6dQnRFrpJMzv0JQIsc4HsSlY
"""

import numpy as np
import matplotlib.pyplot as plt
# Datos de producción diaria antes y después de la inversión en nueva maquinaria
dias = 30 # 30 días de simulación
# Antes de la inversión
produccion_antes = np.random.normal(1000, 50, size=dias) # Producción promedio de 1000
unidades con desviación estándar de 50
# Después de la inversión
produccion_despues = np.random.normal(1500, 50, size=dias) # Producción promedio de
1500 unidades con desviación estándar de 50
# Crear los histogramas
plt.figure(figsize=(12, 6))
# Histograma antes de la inversión
plt.subplot(1, 2, 1)
plt.hist(produccion_antes, bins=10, color='blue', alpha=0.7, edgecolor='black')
plt.axvline(x=1000, color='red', linestyle='--', label='Capacidad Promedio')
plt.title('Producción Antes de la Inversión')
plt.xlabel('Unidades Producidas Diarias')
plt.ylabel('Frecuencia')
plt.legend()
# Histograma después de la inversión
plt.subplot(1, 2, 2)
plt.hist(produccion_despues, bins=10, color='green', alpha=0.7, edgecolor='black')
plt.axvline(x=1500, color='red', linestyle='--', label='Capacidad Promedio')
plt.title('Producción Después de la Inversión')
plt.xlabel('Unidades Producidas Diarias')
plt.ylabel('Frecuencia')
plt.legend()
plt.tight_layout()
plt.show()