# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15HwLsqqn6dQnRFrpJMzv0JQIsc4HsSlY
"""

import matplotlib.pyplot as plt
import numpy as np
# Causas del déficit de producción (antes del outsourcing)
causas = ['Capacidad limitada', 'Falta de personal', 'Problemas en la cadena de suministro',
'Demanda fluctuante', 'Fallas técnicas']
deficit = [500, 300, 200, 100, 100] # Unidades de déficit causadas por cada factor
# Ordenar las causas de mayor a menor impacto
indices_ordenados = np.argsort(deficit)[::-1]
causas_ordenadas = [causas[i] for i in indices_ordenados]
deficit_ordenado = [deficit[i] for i in indices_ordenados]
# Crear el diagrama de Pareto
fig, ax = plt.subplots(figsize=(12, 6)) # Aumentar el tamaño de la figura
ax.bar(causas_ordenadas, deficit_ordenado, color='blue', alpha=0.7)
ax.set_xlabel('Causas del Déficit')
ax.set_ylabel('Déficit en Unidades')
ax.set_title('Diagrama de Pareto - Causas del Déficit de Producción')
# Calcular el porcentaje acumulado
porcentaje_acumulado = np.cumsum(deficit_ordenado) / np.sum(deficit_ordenado) * 100
ax2 = ax.twinx()
ax2.plot(causas_ordenadas, porcentaje_acumulado, color='red', marker='o', linestyle='-',
label='Porcentaje Acumulado')
ax2.set_ylabel('Porcentaje Acumulado')
ax2.grid(False)
# Rotar las etiquetas del eje x para una mejor visualización
plt.xticks(rotation=60, ha='right') # Aumentar la rotación de las etiquetas
plt.tight_layout() # Ajustar el diseño para que no se solapen elementos
plt.show()