# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15HwLsqqn6dQnRFrpJMzv0JQIsc4HsSlY
"""

# Datos de producción antes y después del outsourcing
dias = 30 # 30 días de simulación
# Antes del outsourcing: solo producción interna
produccion_interna_antes = np.random.normal(1000, 50, size=dias) # Producción promedio
de 1000 unidades internas
produccion_externa_antes = np.zeros(dias) # No hay producción externa antes
# Después del outsourcing: producción interna y externa
produccion_interna_despues = np.random.normal(1000, 50, size=dias) # La producción
interna se mantiene en 1000 unidades
produccion_externa_despues = np.random.normal(500, 20, size=dias) # La producción
externa cubre las 500 unidades adicionales
# Crear el diagrama de dispersión
plt.figure(figsize=(12, 6))
# Dispersión antes del outsourcing
plt.subplot(1, 2, 1)
plt.scatter(produccion_interna_antes, produccion_externa_antes, color='blue')
plt.title('Producción Antes del Outsourcing')
plt.xlabel('Producción Interna (Unidades)')
plt.ylabel('Producción Externa (Unidades)')
# Dispersión después del outsourcing
plt.subplot(1, 2, 2)
plt.scatter(produccion_interna_despues, produccion_externa_despues, color='green')
plt.title('Producción Después del Outsourcing')
plt.xlabel('Producción Interna (Unidades)')
plt.ylabel('Producción Externa (Unidades)')
plt.tight_layout()
plt.show()