# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15HwLsqqn6dQnRFrpJMzv0JQIsc4HsSlY
"""

# Crear histogramas para antes y después
plt.figure(figsize=(12, 6))
# Histograma antes de contratar personal adicional
plt.subplot(1, 2, 1)
plt.hist(produccion_antes, bins=10, color='blue', alpha=0.7)
plt.title('Histograma de Producción (Antes)')
plt.xlabel('Producción Diaria (Unidades)')
plt.ylabel('Frecuencia')
# Histograma después de contratar personal adicional
plt.subplot(1, 2, 2)
plt.hist(produccion_despues, bins=10, color='green', alpha=0.7)
plt.title('Histograma de Producción (Después)')
plt.xlabel('Producción Diaria (Unidades)')
plt.ylabel('Frecuencia')
plt.tight_layout()
plt.show()