# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15HwLsqqn6dQnRFrpJMzv0JQIsc4HsSlY
"""

# Datos simulados: Disponibilidad de materias primas y producción diaria
disponibilidad_antes = np.random.normal(60, 10, size=30) # Disponibilidad en % antes de la
mejora
produccion_antes = np.random.normal(900, 50, size=30) # Producción antes de la mejora
disponibilidad_despues = np.random.normal(90, 5, size=30) # Disponibilidad en % después
de la mejora
produccion_despues = np.random.normal(1200, 50, size=30) # Producción después de la
mejora
# Crear el Diagrama de Dispersión
plt.figure(figsize=(10, 5))
# Dispersión antes de la mejora
plt.subplot(1, 2, 1)
plt.scatter(disponibilidad_antes, produccion_antes, color='blue')
plt.title('Diagrama de Dispersión (Antes)')
plt.xlabel('Disponibilidad de Materias Primas (%)')
plt.ylabel('Producción Diaria (Unidades)')
plt.grid(True)
# Dispersión después de la mejora
plt.subplot(1, 2, 2)
plt.scatter(disponibilidad_despues, produccion_despues, color='green')
plt.title('Diagrama de Dispersión (Después)')
plt.xlabel('Disponibilidad de Materias Primas (%)')
plt.ylabel('Producción Diaria (Unidades)')
plt.grid(True)
plt.tight_layout()
plt.show()